package com.locydragon.myinv.core.script;

public enum JobCodeEnum {
	PLAYER_CMD,CONSOLE_CMD,OP_CMD,ASK,CLOSE,MONEY,MESSAGE,POINTS,XP, //给予类型(注:经验给予的api有bug,停止使用)
	IS_NUMBER,HAS_PERMISSION,COMPARE,
	COST,COST_POINT,ITEM_COST_BY_NAME,ITEM_COST_BY_ENGLISH_NAME
}
